ecampus/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('role/', include('role.urls')),
    path('user/', include('userapp.urls')),

]

role/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

urlpatterns = [
     path('',views.index,name='index')

]

userapp/urls.py
from os import name
from pathlib import Path
from django import views
from django.urls import path
from .views import *
from django.contrib.auth.views import LoginView, LogoutView
#from .views import UserLoginView
from .views import UserLoginView, BaseRegisterView
from . import views      

app_name = 'ecampus_urls'

urlpatterns = [
    path("registration/",BaseRegisterView.as_view(),name="registration"),
    path("user-login/", UserLoginView.as_view() ,name='user-login'),
    path("index/",views.index),
    # path('view/', ViewUser.as_view(), name="view_user"),
    # path('<int:pk>/detail/',DetailUser.as_view()),

]

templates/userportal/registration.html
{% load static %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en" >
	<head>
		<meta charset="utf-8">
		<title>Registration Form</title>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">

		<!-- MATERIAL DESIGN ICONIC FONT -->
		{% comment %} <link rel="stylesheet" href="{% static 'user/material-design-iconic-font.min.css' %}"/> {% endcomment %}
		{% comment %} <link rel="stylesheet" href="fonts/material-design-iconic-font/css/material-design-iconic-font.min.css"> {% endcomment %}
		
		<!-- STYLE CSS -->
		<link rel="stylesheet" href="{% static 'user/style.css' %}"/>
	</head>

	<body>
		{% comment %} This is for add image {% endcomment %}
		<div class="wrapper" style="background-image: url('{% static 'user/image/Ecampus (6).jpg'%}');"> 
			
			<div class="inner">
				<form action="#" method="POST" data-toggle="validator" role="form">
					{% csrf_token %}
					{{form.as_p}}
					<h3>Registration Form</h3>
					<div class="form-group">
						<div class="form-wrapper">
							<label for="">Username:</label>
							<div class="form-holder">
								<i class="zmdi zmdi-account-o"></i>
								<input type="text" class="form-control">
							</div>
						</div>
						<div class="form-wrapper">
							<label for="">Email:</label>
							<div class="form-holder">
								<i style="font-style: normal; font-size: 15px;">@</i>
								<input type="text" class="form-control">
							</div>
						</div>
					</div>
					<div class="form-group">
						<div class="form-wrapper">
							<label for="">Password:</label>
							<div class="form-holder">
								<i class="zmdi zmdi-lock-outline"></i>
								<input type="password" class="form-control" placeholder="********">
							</div>
						</div>
						<div class="form-wrapper">
							<label for="">Repeat Password:</label>
							<div class="form-holder">
								<i class="zmdi zmdi-lock-outline"></i>
								<input type="password" class="form-control" placeholder="********">
							</div>
						</div>
					</div>
					<div class="form-group">
						<div class="form-wrapper">
							<label for="">Country:</label>
							<div class="form-holder select">
								<select name="" id="" class="form-control">
									<option value="united states">India</option>
									<option value="united states">United States</option>
									<option value="viet nam">UAE</option>
									<option value="united kingdom">United Kingdom</option>
									<option value="viet nam">Viet Nam</option>

								</select>
								<i class="zmdi zmdi-pin"></i>
							</div>
						</div>
						<div class="form-wrapper">
							<label for="">Gender:</label>
							<div class="form-holder select">
								<select name="" id="" class="form-control">
									<option value="male">Male</option>
									<option value="femal">Female</option>
									<option value="other">Other</option>
								</select>
								<i class="zmdi zmdi-face"></i>
							</div>
						</div>
					</div>
					<div class="form-end">
						<div class="checkbox">
							<label>
								<input type="checkbox"> Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt.
								<span class="checkmark"></span>
							</label>
						</div>
						<div class="action">
							{% comment %} <input type="submit" value="submit" button="Register"> {% endcomment %}
							<button type="submit">Register Now</button>
						</div>
						
					</div>
				</form>
			</div>
		</div>
		
	</body>
</html>

templates/userportal/user_login.html
{% load static %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en" >
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Login Template</title>
  <link href="https://fonts.googleapis.com/css?family=Karla:400,700&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="https://cdn.materialdesignicons.com/4.8.95/css/materialdesignicons.min.css">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
  <link rel="stylesheet" href="{% static 'user/login.css' %}"/>
</head>
<body>
  <main class="d-flex align-items-center min-vh-100 py-3 py-md-0">
    <div class="container">
      <div class="card login-card">
        <div class="row no-gutters">
          <div class="col-md-5">
            <img src="{% static "user/image/study (1).jpg" %}" alt="login" class="login-card-img">
          </div>
          <div class="col-md-7">
            <div class="card-body">
              <div class="brand-wrapper">
                <img src="{% static "user/image/logo.svg" %}" alt="logo" class="logo">
              </div>
              <p class="login-card-description">Sign into your account</p>
              <form method="POST">
				      {% csrf_token %}
                  <div class="form-group">
                    <label for="Username" class="sr-only">Username</label>
                    {% comment %} <input type="text" name="Username" id="#" class="form-control" placeholder="Username"> {% endcomment %}
                    {{form.username | as_crispy_field}}
                  </div>
                  <div class="form-group mb-4">
                    <label for="password" class="sr-only">Password</label>
                    <input type="password" name="password" id="password" class="form-control" placeholder="***********">
                  </div>
                  <input name="login" id="login" class="btn btn-block login-btn mb-4" type="submit" value="Login">
                  {% comment %} {{form.password | as_crispy_field}} {% endcomment %}

                </form>
                <a href="#!" class="forgot-password-link">Forgot password?</a> 
                <p class="login-card-footer-text">Don't have an account? <a href= "{% url 'ecampus_urls:registration' %}" class="text-reset">Register here</a></p>
                <nav class="login-card-footer-nav">
                  <a href="#!">Terms of use.</a>
                  <a href="#!">Privacy policy</a>
                </nav>
            </div>
          </div>
        </div>
      </div>
      <!-- <div class="card login-card">
        <img src="assets/images/login.jpg" alt="login" class="login-card-img">
        <div class="card-body">
          <h2 class="login-card-title">Login</h2>
          <p class="login-card-description">Sign in to your account to continue.</p>
          <form action="#!">
            <div class="form-group">
              <label for="email" class="sr-only">Email</label>
              <input type="email" name="email" id="email" class="form-control" placeholder="Email">
            </div>
            <div class="form-group">
              <label for="password" class="sr-only">Password</label>
              <input type="password" name="password" id="password" class="form-control" placeholder="Password">
            </div>
            <div class="form-prompt-wrapper">
              <div class="custom-control custom-checkbox login-card-check-box">
                <input type="checkbox" class="custom-control-input" id="customCheck1">
                <label class="custom-control-label" for="customCheck1">Remember me</label>
              </div>              
              <a href="#!" class="text-reset">Forgot password?</a>
            </div>
            <input name="login" id="login" class="btn btn-block login-btn mb-4" type="button" value="Login">
          </form>
          <p class="login-card-footer-text">Don't have an account? <a href="#!" class="text-reset">Register here</a></p>
        </div>
      </div> -->
    </div>
  </main>
  <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
</body>
</html>